### ISSUE TITLE
Invalid player data when trying to join server

### ISSUE THREAD

**Issue by flashifloosh** [BluSpring/UnityTranslate#7]
When trying to join a server with the mod (including simplevoice) installed, it gives this stacktrace

```
[14:09:58] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_9139.encode(Object, Object)" because "codec" is null
	at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.6-fabric.jar:?]
	at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.6-fabric.jar:?]
	at xyz.bluspring.unitytranslate.PlatformProxy$DefaultImpls.sendPacketServer(PlatformProxy.kt:45) ~[UnityTranslate-0.2.0-beta+mc1.21.1-fabric.jar:?]
	at xyz.bluspring.unitytranslate.PlatformProxyImpl.sendPacketServer(PlatformProxyImpl.kt:30) ~[UnityTranslate-0.2.0-beta+mc1.21.1-fabric.jar:?]
	at xyz.bluspring.unitytranslate.network.UTServerNetworking.init$lambda$15(UTServerNetworking.kt:170) ~[UnityTranslate-0.2.0-beta+mc1.21.1-fabric.jar:?]
	at net.minecraft.server.PlayerManager.handler$zia000$architectury$placeNewPlayer(PlayerManager.java:2009) ~[server-intermediary.jar:?]
	at net.minecraft.server.PlayerManager.onPlayerConnect(PlayerManager.java:288) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerConfigurationNetworkHandler.onReady(ServerConfigurationNetworkHandler.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.network.packet.c2s.config.ReadyC2SPacket.apply(ReadyC2SPacket.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.network.packet.c2s.config.ReadyC2SPacket.apply(ReadyC2SPacket.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasks(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
``` 

Minecraft version: 1.21.1 Fabric 0.16.5
UT version: v0.1.12-beta

**Comment by BluSpring** [comment]
No, according to your log, you are most definitely not using v0.1.12-beta.
You are currently using the latest build from the GitHub Actions for v0.2.0-beta, which is currently very broken in most environments at the moment.

Please download an official build from [Modrinth](https://modrinth.com/mod/unitytranslate) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/unitytranslate).

**Comment by flashifloosh** [comment]
Whoops! I actually tried both versions. Here's the log with the v0.1.12-beta
```
Cannot invoke "net.minecraft.class_9139.encode(Object, Object)" because "codec" is null
        at dev.architectury.impl.NetworkAggregator.collectPackets(NetworkAggregator.java:146) ~[architectury-13.0.8-fabric.jar:?]
        at dev.architectury.networking.NetworkManager.collectPackets(NetworkManager.java:137) ~[architectury-13.0.8-fabric.jar:?]
        at dev.architectury.networking.NetworkManager.sendToPlayer(NetworkManager.java:157) ~[architectury-13.0.8-fabric.jar:?]
        at xyz.bluspring.unitytranslate.PlatformProxy$DefaultImpls.sendPacketServer(PlatformProxy.kt:45) ~[UnityTranslate-0.1.12-beta+1.21.1-fabric.jar:?]
        at xyz.bluspring.unitytranslate.PlatformProxyImpl.sendPacketServer(PlatformProxyImpl.kt:30) ~[UnityTranslate-0.1.12-beta+1.21.1-fabric.jar:?]
        at xyz.bluspring.unitytranslate.network.UTServerNetworking.init$lambda$15(UTServerNetworking.kt:170) ~[UnityTranslate-0.1.12-beta+1.21.1-fabric.jar:?]
        at net.minecraft.class_3324.handler$zbm000$architectury$placeNewPlayer(class_3324.java:1009) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:288) ~[server-intermediary.jar:?]
        at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
```

**Comment by Hinzy-Admin** [comment]
having the same issue on fabric 1.21.1
